# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5f5667b19d304dae818094153bda92d5bf0c6f8bf5e8d77e4aee7fb7a8cfd43b73e359c6e181a619531fae446f05691f3be29c0f1c1df057ffe107e089bbcee

test:
  secret_key_base: 80f00be3671507d2ce7dca319a9d7dba91af42b0faf843ed810f0d0e6bf9f77f6faff0799c1e1cd7dc848fe32b57a454228efcf97f7d0f8aec2ce1272ff0d10b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
